// Источники терминов: "Библейский словарь Гезе" на azbyka.ru — см. `https://azbyka.ru/otechnik/Spravochniki/biblejskij-slovar-gese`
// Слова разделены на базовый и усложненный режимы для разных уровней подготовки

export type AliasWord = {
  term: string;
  hint?: string;
  category: string;
  difficulty: 'basic' | 'advanced'; // базовый или усложненный режим
};

export type AliasCategory = {
  key: string;
  title: string;
  description?: string;
  words: AliasWord[];
};

export const aliasCategories: AliasCategory[] = [
  {
    key: 'persons',
    title: 'Библейские личности',
    description: 'Имена людей из Библии',
    words: [
      // Базовый режим - знакомые всем
      { term: 'Адам', category: 'Библейские личности', hint: 'Первый человек', difficulty: 'basic' },
      { term: 'Ева', category: 'Библейские личности', hint: 'Первая женщина', difficulty: 'basic' },
      { term: 'Авраам', category: 'Библейские личности', hint: 'Отец многих народов', difficulty: 'basic' },
      { term: 'Исаак', category: 'Библейские личности', hint: 'Сын обетования', difficulty: 'basic' },
      { term: 'Иаков', category: 'Библейские личности', hint: 'Израиль', difficulty: 'basic' },
      { term: 'Иосиф', category: 'Библейские личности', hint: 'Сны, Египет', difficulty: 'basic' },
      { term: 'Моисей', category: 'Библейские личности', hint: 'Исход', difficulty: 'basic' },
      { term: 'Давид', category: 'Библейские личности', hint: 'Царь, Псалмы', difficulty: 'basic' },
      { term: 'Соломон', category: 'Библейские личности', hint: 'Мудрость', difficulty: 'basic' },
      { term: 'Иисус', category: 'Библейские личности', hint: 'Спаситель', difficulty: 'basic' },
      { term: 'Мария', category: 'Библейские личности', hint: 'Богородица', difficulty: 'basic' },
      { term: 'Пётр', category: 'Библейские личности', hint: 'Апостол', difficulty: 'basic' },
      { term: 'Павел', category: 'Библейские личности', hint: 'Апостол язычников', difficulty: 'basic' },
      { term: 'Ной', category: 'Библейские личности', hint: 'Ковчег, потоп', difficulty: 'basic' },
      { term: 'Иоанн', category: 'Библейские личности', hint: 'Возлюбленный ученик', difficulty: 'basic' },
      
      // Усложненный режим - для знающих Библию
      { term: 'Иисус Навин', category: 'Библейские личности', hint: 'Преемник Моисея', difficulty: 'advanced' },
      { term: 'Илия', category: 'Библейские личности', hint: 'Пророк огня', difficulty: 'advanced' },
      { term: 'Исаия', category: 'Библейские личности', hint: 'Великий пророк', difficulty: 'advanced' },
      { term: 'Иеремия', category: 'Библейские личности', hint: 'Плачущий пророк', difficulty: 'advanced' },
      { term: 'Даниил', category: 'Библейские личности', hint: 'Львиный ров', difficulty: 'advanced' },
      { term: 'Иоанн Креститель', category: 'Библейские личности', hint: 'Предтеча', difficulty: 'advanced' },
      { term: 'Иосиф Обручник', category: 'Библейские личности', hint: 'Муж Марии', difficulty: 'advanced' },
      { term: 'Лот', category: 'Библейские личности', hint: 'Содом и Гоморра', difficulty: 'advanced' },
      { term: 'Сара', category: 'Библейские личности', hint: 'Мать народов', difficulty: 'advanced' },
      { term: 'Ревекка', category: 'Библейские личности', hint: 'Мать близнецов', difficulty: 'advanced' },
      { term: 'Рахиль', category: 'Библейские личности', hint: 'Любимая жена', difficulty: 'advanced' },
      { term: 'Лия', category: 'Библейские личности', hint: 'Первая жена', difficulty: 'advanced' },
      { term: 'Руфь', category: 'Библейские личности', hint: 'Моавитянка', difficulty: 'advanced' },
      { term: 'Самуил', category: 'Библейские личности', hint: 'Пророк и судья', difficulty: 'advanced' },
      { term: 'Саул', category: 'Библейские личности', hint: 'Первый царь Израиля', difficulty: 'advanced' },
      { term: 'Елисей', category: 'Библейские личности', hint: 'Ученик Илии', difficulty: 'advanced' },
      { term: 'Ездра', category: 'Библейские личности', hint: 'Книжник', difficulty: 'advanced' },
      { term: 'Неемия', category: 'Библейские личности', hint: 'Строитель стен', difficulty: 'advanced' },
      { term: 'Есфирь', category: 'Библейские личности', hint: 'Царица Персии', difficulty: 'advanced' },
      { term: 'Иов', category: 'Библейские личности', hint: 'Страдалец', difficulty: 'advanced' },
      { term: 'Иона', category: 'Библейские личности', hint: 'Пророк в чреве кита', difficulty: 'advanced' },
      { term: 'Малахия', category: 'Библейские личности', hint: 'Последний пророк', difficulty: 'advanced' },
      { term: 'Захария', category: 'Библейские личности', hint: 'Пророк', difficulty: 'advanced' },
      { term: 'Аггей', category: 'Библейские личности', hint: 'Пророк', difficulty: 'advanced' },
      { term: 'Софония', category: 'Библейские личности', hint: 'Пророк', difficulty: 'advanced' },
      { term: 'Аввакум', category: 'Библейские личности', hint: 'Пророк', difficulty: 'advanced' },
      { term: 'Наум', category: 'Библейские личности', hint: 'Пророк', difficulty: 'advanced' },
      { term: 'Михей', category: 'Библейские личности', hint: 'Пророк', difficulty: 'advanced' },
      { term: 'Амос', category: 'Библейские личности', hint: 'Пророк', difficulty: 'advanced' },
      { term: 'Иоиль', category: 'Библейские личности', hint: 'Пророк', difficulty: 'advanced' },
      { term: 'Осия', category: 'Библейские личности', hint: 'Пророк', difficulty: 'advanced' },
      { term: 'Иезекииль', category: 'Библейские личности', hint: 'Пророк', difficulty: 'advanced' },
      { term: 'Варфоломей', category: 'Библейские личности', hint: 'Апостол', difficulty: 'advanced' },
      { term: 'Фома', category: 'Библейские личности', hint: 'Неверующий апостол', difficulty: 'advanced' },
      { term: 'Матфей', category: 'Библейские личности', hint: 'Мытарь-апостол', difficulty: 'advanced' },
      { term: 'Иаков Алфеев', category: 'Библейские личности', hint: 'Апостол', difficulty: 'advanced' },
      { term: 'Симон Зилот', category: 'Библейские личности', hint: 'Апостол', difficulty: 'advanced' },
      { term: 'Иуда Искариот', category: 'Библейские личности', hint: 'Предатель', difficulty: 'advanced' },
      { term: 'Марфа', category: 'Библейские личности', hint: 'Сестра Лазаря', difficulty: 'advanced' },
      { term: 'Мария Магдалина', category: 'Библейские личности', hint: 'Первая увидела воскресшего', difficulty: 'advanced' },
      { term: 'Лазарь', category: 'Библейские личности', hint: 'Воскрешённый из мёртвых', difficulty: 'advanced' },
      { term: 'Никодим', category: 'Библейские личности', hint: 'Фарисей, учитель', difficulty: 'advanced' },
      { term: 'Иосиф Аримафейский', category: 'Библейские личности', hint: 'Подал гроб для Спасителя', difficulty: 'advanced' },
      { term: 'Стефан', category: 'Библейские личности', hint: 'Первомученик', difficulty: 'advanced' },
      { term: 'Варнава', category: 'Библейские личности', hint: 'Спутник Павла', difficulty: 'advanced' },
      { term: 'Тимофей', category: 'Библейские личности', hint: 'Ученик Павла', difficulty: 'advanced' },
      { term: 'Тит', category: 'Библейские личности', hint: 'Ученик Павла', difficulty: 'advanced' },
      { term: 'Филимон', category: 'Библейские личности', hint: 'Хозяин Онисима', difficulty: 'advanced' },
      { term: 'Онисим', category: 'Библейские личности', hint: 'Беглый раб', difficulty: 'advanced' },
      { term: 'Симеон', category: 'Библейские личности', hint: 'Благочестивый старец', difficulty: 'advanced' },
      { term: 'Анна', category: 'Библейские личности', hint: 'Пророчица в храме', difficulty: 'advanced' },
      { term: 'Елизавета', category: 'Библейские личности', hint: 'Мать Предтечи', difficulty: 'advanced' },
      { term: 'Авессалом', category: 'Библейские личности', hint: 'Сын царя', difficulty: 'advanced' },
      { term: 'Вениамин', category: 'Библейские личности', hint: 'Младший сын', difficulty: 'advanced' },
      { term: 'Иуда', category: 'Библейские личности', hint: 'Продал брата', difficulty: 'advanced' },
      { term: 'Кирьят-Иарим', category: 'Библейские личности', hint: 'Город леса', difficulty: 'advanced' },
      { term: 'Иевус', category: 'Библейские личности', hint: 'Древнее название Иерусалима', difficulty: 'advanced' },
      { term: 'Милло', category: 'Библейские личности', hint: 'Крепость в Иерусалиме', difficulty: 'advanced' },
      { term: 'Офел', category: 'Библейские личности', hint: 'Холм в Иерусалиме', difficulty: 'advanced' },
      { term: 'Кедрон', category: 'Библейские личности', hint: 'Долина в Иерусалиме', difficulty: 'advanced' },
      { term: 'Гефсимания', category: 'Библейские личности', hint: 'Сад молитвы', difficulty: 'advanced' },
      { term: 'Елеонская гора', category: 'Библейские личности', hint: 'Гора Вознесения', difficulty: 'advanced' },
      { term: 'Фавор', category: 'Библейские личности', hint: 'Гора Преображения', difficulty: 'advanced' },
      { term: 'Капернаум', category: 'Библейские личности', hint: 'Город на берегу моря', difficulty: 'advanced' },
      { term: 'Кана', category: 'Библейские личности', hint: 'Место первого чуда', difficulty: 'advanced' },
      { term: 'Вифания', category: 'Библейские личности', hint: 'Дом Лазаря', difficulty: 'advanced' },
      { term: 'Виффагия', category: 'Библейские личности', hint: 'Дом смокв', difficulty: 'advanced' },
      { term: 'Эммаус', category: 'Библейские личности', hint: 'Деревня на пути', difficulty: 'advanced' },
      { term: 'Антиохия', category: 'Библейские личности', hint: 'Город Павла', difficulty: 'advanced' },
      { term: 'Эфес', category: 'Библейские личности', hint: 'Город церкви', difficulty: 'advanced' },
      { term: 'Коринф', category: 'Библейские личности', hint: 'Город Павла', difficulty: 'advanced' },
      { term: 'Фессалоника', category: 'Библейские личности', hint: 'Город Павла', difficulty: 'advanced' },
      { term: 'Филиппы', category: 'Библейские личности', hint: 'Город Павла', difficulty: 'advanced' },
      { term: 'Колоски', category: 'Библейские личности', hint: 'Город церкви', difficulty: 'advanced' },
      { term: 'Рим', category: 'Библейские личности', hint: 'Столица империи', difficulty: 'advanced' },
      { term: 'Дамаск', category: 'Библейские личности', hint: 'Город обращения Павла', difficulty: 'advanced' },
      { term: 'Аарон', category: 'Библейские личности', hint: 'Первосвященник, брат Моисея', difficulty: 'advanced' },
      { term: 'Мириам', category: 'Библейские личности', hint: 'Сестра Моисея', difficulty: 'advanced' },
      { term: 'Иисус Навин', category: 'Библейские личности', hint: 'Преемник Моисея', difficulty: 'advanced' },
      { term: 'Гедеон', category: 'Библейские личности', hint: 'Судья Израиля', difficulty: 'advanced' },
      { term: 'Самсон', category: 'Библейские личности', hint: 'Силач-судья', difficulty: 'advanced' },
      { term: 'Девора', category: 'Библейские личности', hint: 'Пророчица-судья', difficulty: 'advanced' },
      { term: 'Иеффай', category: 'Библейские личности', hint: 'Судья Израиля', difficulty: 'advanced' },
      { term: 'Авессалом', category: 'Библейские личности', hint: 'Мятежный сын Давида', difficulty: 'advanced' },
      { term: 'Адония', category: 'Библейские личности', hint: 'Сын Давида', difficulty: 'advanced' },
      { term: 'Ахав', category: 'Библейские личности', hint: 'Царь Израиля', difficulty: 'advanced' },
      { term: 'Иезавель', category: 'Библейские личности', hint: 'Жена Ахава', difficulty: 'advanced' },
      { term: 'Иосафат', category: 'Библейские личности', hint: 'Царь Иудеи', difficulty: 'advanced' },
      { term: 'Езекия', category: 'Библейские личности', hint: 'Царь Иудеи', difficulty: 'advanced' },
      { term: 'Манассия', category: 'Библейские личности', hint: 'Царь Иудеи', difficulty: 'advanced' },
      { term: 'Иосия', category: 'Библейские личности', hint: 'Царь-реформатор', difficulty: 'advanced' },
      { term: 'Зоровавель', category: 'Библейские личности', hint: 'Вождь возвращения', difficulty: 'advanced' },
      { term: 'Иисус сын Сирахов', category: 'Библейские личности', hint: 'Автор Премудрости', difficulty: 'advanced' },
      { term: 'Тарс', category: 'Библейские личности', hint: 'Родина Павла', difficulty: 'advanced' },
      { term: 'Кесария', category: 'Библейские личности', hint: 'Город Пилата', difficulty: 'advanced' },
      { term: 'Иоппия', category: 'Библейские личности', hint: 'Город Ионы', difficulty: 'advanced' },
      { term: 'Аскалон', category: 'Библейские личности', hint: 'Город филистимлян', difficulty: 'advanced' },
      { term: 'Газ', category: 'Библейские личности', hint: 'Город Самсона', difficulty: 'advanced' },
      { term: 'Азот', category: 'Библейские личности', hint: 'Город филистимлян', difficulty: 'advanced' },
      { term: 'Геф', category: 'Библейские личности', hint: 'Город Голиафа', difficulty: 'advanced' },
      { term: 'Екрон', category: 'Библейские личности', hint: 'Город филистимлян', difficulty: 'advanced' },
      { term: 'Акра', category: 'Библейские личности', hint: 'Крепость в Иерусалиме', difficulty: 'advanced' },
      { term: 'Башня Давида', category: 'Библейские личности', hint: 'Крепость в Иерусалиме', difficulty: 'advanced' },
      { term: 'Храмовая гора', category: 'Библейские личности', hint: 'Место храма', difficulty: 'advanced' },
      { term: 'Стена плача', category: 'Библейские личности', hint: 'Западная стена храма', difficulty: 'advanced' },
      { term: 'Купол скалы', category: 'Библейские личности', hint: 'Мечеть на храмовой горе', difficulty: 'advanced' },
      { term: 'Храм Гроба Господня', category: 'Библейские личности', hint: 'Место распятия', difficulty: 'advanced' },
      { term: 'Вифлеемская звезда', category: 'Библейские личности', hint: 'Путеводная звезда', difficulty: 'advanced' },
      { term: 'Мертвое море', category: 'Библейские личности', hint: 'Солёное озеро', difficulty: 'advanced' },
      { term: 'Галилейское море', category: 'Библейские личности', hint: 'Озеро Тивериадское', difficulty: 'advanced' },
      { term: 'Иордан', category: 'Библейские личности', hint: 'Река крещения', difficulty: 'advanced' },
      { term: 'Нил', category: 'Библейские личности', hint: 'Река Египта', difficulty: 'advanced' },
      { term: 'Евфрат', category: 'Библейские личности', hint: 'Река Вавилона', difficulty: 'advanced' },
      { term: 'Тигр', category: 'Библейские личности', hint: 'Река Ассирии', difficulty: 'advanced' },
      { term: 'Красное море', category: 'Библейские личности', hint: 'Море исхода', difficulty: 'advanced' },
      { term: 'Средиземное море', category: 'Библейские личности', hint: 'Великое море', difficulty: 'advanced' },
      { term: 'Чёрное море', category: 'Библейские личности', hint: 'Понт', difficulty: 'advanced' },
      { term: 'Каспийское море', category: 'Библейские личности', hint: 'Море Каспий', difficulty: 'advanced' },
      { term: 'Персидский залив', category: 'Библейские личности', hint: 'Залив Персии', difficulty: 'advanced' },
      { term: 'Аравийская пустыня', category: 'Библейские личности', hint: 'Пустыня Аравии', difficulty: 'advanced' },
      { term: 'Синайская пустыня', category: 'Библейские личности', hint: 'Пустыня закона', difficulty: 'advanced' },
      { term: 'Негев', category: 'Библейские личности', hint: 'Южная пустыня', difficulty: 'advanced' },
      { term: 'Иудейская пустыня', category: 'Библейские личности', hint: 'Пустыня Иудеи', difficulty: 'advanced' },
      { term: 'Самарийская пустыня', category: 'Библейские личности', hint: 'Пустыня Самарии', difficulty: 'advanced' },
      { term: 'Галилейская пустыня', category: 'Библейские личности', hint: 'Пустыня Галилеи', difficulty: 'advanced' },
      { term: 'Иорданская долина', category: 'Библейские личности', hint: 'Долина реки', difficulty: 'advanced' },
      { term: 'Изреельская долина', category: 'Библейские личности', hint: 'Долина Изреель', difficulty: 'advanced' },
      { term: 'Шефела', category: 'Библейские личности', hint: 'Предгорье', difficulty: 'advanced' },
      { term: 'Нефалим', category: 'Библейские личности', hint: 'Северная область', difficulty: 'advanced' },
      { term: 'Ашер', category: 'Библейские личности', hint: 'Западная область', difficulty: 'advanced' },
      { term: 'Завулон', category: 'Библейские личности', hint: 'Приморская область', difficulty: 'advanced' },
      { term: 'Иссахар', category: 'Библейские личности', hint: 'Центральная область', difficulty: 'advanced' },
      { term: 'Манассия', category: 'Библейские личности', hint: 'Восточная область', difficulty: 'advanced' },
      { term: 'Ефрем', category: 'Библейские личности', hint: 'Центральная область', difficulty: 'advanced' },
      { term: 'Вениамин', category: 'Библейские личности', hint: 'Южная область', difficulty: 'advanced' },
      { term: 'Иуда', category: 'Библейские личности', hint: 'Южная область', difficulty: 'advanced' },
      { term: 'Дан', category: 'Библейские личности', hint: 'Южная область', difficulty: 'advanced' },
      { term: 'Симеон', category: 'Библейские личности', hint: 'Южная область', difficulty: 'advanced' },
      { term: 'Рувим', category: 'Библейские личности', hint: 'Восточная область', difficulty: 'advanced' },
      { term: 'Гад', category: 'Библейские личности', hint: 'Восточная область', difficulty: 'advanced' },
      { term: 'Леви', category: 'Библейские личности', hint: 'Священническая область', difficulty: 'advanced' },
    ],
  },
  {
    key: 'places',
    title: 'Места и география',
    description: 'Города, страны, области из Библии',
    words: [
      // Базовый режим - знакомые всем
      { term: 'Иерусалим', category: 'Места и география', hint: 'Святой город', difficulty: 'basic' },
      { term: 'Вифлеем', category: 'Места и география', hint: 'Город рождения', difficulty: 'basic' },
      { term: 'Назарет', category: 'Места и география', hint: 'Город детства', difficulty: 'basic' },
      { term: 'Египет', category: 'Места и география', hint: 'Земля фараонов', difficulty: 'basic' },
      { term: 'Вавилон', category: 'Места и география', hint: 'Вавилонская башня', difficulty: 'basic' },
      { term: 'Рим', category: 'Места и география', hint: 'Столица империи', difficulty: 'basic' },
      { term: 'Голгофа', category: 'Места и география', hint: 'Место распятия', difficulty: 'basic' },
      { term: 'Сион', category: 'Места и география', hint: 'Гора в Иерусалиме', difficulty: 'basic' },
      
      // Усложненный режим - для знающих Библию
      { term: 'Ассирия', category: 'Места и география', hint: 'Древняя империя', difficulty: 'advanced' },
      { term: 'Галилея', category: 'Места и география', hint: 'Северная область', difficulty: 'advanced' },
      { term: 'Самария', category: 'Места и география', hint: 'Центральная область', difficulty: 'advanced' },
      { term: 'Иудея', category: 'Места и география', hint: 'Южная область', difficulty: 'advanced' },
      { term: 'Мориа', category: 'Места и география', hint: 'Гора жертвоприношения', difficulty: 'advanced' },
      { term: 'Кармил', category: 'Места и география', hint: 'Гора пророков', difficulty: 'advanced' },
      { term: 'Хеврон', category: 'Места и география', hint: 'Город патриархов', difficulty: 'advanced' },
      { term: 'Ханаан', category: 'Места и география', hint: 'Земля обетованная', difficulty: 'advanced' },
      { term: 'Месопотамия', category: 'Места и география', hint: 'Междуречье', difficulty: 'advanced' },
      { term: 'Ур', category: 'Места и география', hint: 'Древний город', difficulty: 'advanced' },
      { term: 'Харран', category: 'Места и география', hint: 'Город на пути в Ханаан', difficulty: 'advanced' },
      { term: 'Вефиль', category: 'Места и география', hint: 'Дом Божий', difficulty: 'advanced' },
      { term: 'Сихем', category: 'Места и география', hint: 'Город колодца', difficulty: 'advanced' },
      { term: 'Мамре', category: 'Места и география', hint: 'Дубрава патриархов', difficulty: 'advanced' },
      { term: 'Содом', category: 'Места и география', hint: 'Город греха', difficulty: 'advanced' },
      { term: 'Гоморра', category: 'Места и география', hint: 'Город греха', difficulty: 'advanced' },
      { term: 'Хар-Гаризим', category: 'Места и география', hint: 'Гора благословения', difficulty: 'advanced' },
      { term: 'Гевал', category: 'Места и география', hint: 'Гора проклятия', difficulty: 'advanced' },
      { term: 'Иерихон', category: 'Места и география', hint: 'Город труб', difficulty: 'advanced' },
      { term: 'Ай', category: 'Места и география', hint: 'Город развалин', difficulty: 'advanced' },
      { term: 'Гива', category: 'Места и география', hint: 'Город Саула', difficulty: 'advanced' },
      { term: 'Рама', category: 'Места и география', hint: 'Город Самуила', difficulty: 'advanced' },
      { term: 'Мицпа', category: 'Места и география', hint: 'Место собрания', difficulty: 'advanced' },
      { term: 'Гилгал', category: 'Места и география', hint: 'Место обрезания', difficulty: 'advanced' },
      { term: 'Силом', category: 'Места и география', hint: 'Место скинии', difficulty: 'advanced' },
      { term: 'Антиохия', category: 'Места и география', hint: 'Город Павла', difficulty: 'advanced' },
      { term: 'Эфес', category: 'Места и география', hint: 'Город церкви', difficulty: 'advanced' },
      { term: 'Коринф', category: 'Места и география', hint: 'Город Павла', difficulty: 'advanced' },
      { term: 'Фессалоника', category: 'Места и география', hint: 'Город Павла', difficulty: 'advanced' },
      { term: 'Филиппы', category: 'Места и география', hint: 'Город Павла', difficulty: 'advanced' },
      { term: 'Колоски', category: 'Места и география', hint: 'Город церкви', difficulty: 'advanced' },
      { term: 'Дамаск', category: 'Места и география', hint: 'Город обращения Павла', difficulty: 'advanced' },
      { term: 'Тарс', category: 'Места и география', hint: 'Родина Павла', difficulty: 'advanced' },
      { term: 'Кесария', category: 'Места и география', hint: 'Город Пилата', difficulty: 'advanced' },
      { term: 'Иоппия', category: 'Места и география', hint: 'Город Ионы', difficulty: 'advanced' },
      { term: 'Аскалон', category: 'Места и география', hint: 'Город филистимлян', difficulty: 'advanced' },
      { term: 'Газ', category: 'Места и география', hint: 'Город Самсона', difficulty: 'advanced' },
      { term: 'Азот', category: 'Места и география', hint: 'Город филистимлян', difficulty: 'advanced' },
      { term: 'Геф', category: 'Места и география', hint: 'Город Голиафа', difficulty: 'advanced' },
      { term: 'Екрон', category: 'Места и география', hint: 'Город филистимлян', difficulty: 'advanced' },
      { term: 'Вавилон', category: 'Места и география', hint: 'Город плена', difficulty: 'advanced' },
      { term: 'Сузы', category: 'Места и география', hint: 'Столица Персии', difficulty: 'advanced' },
      { term: 'Ниневия', category: 'Места и география', hint: 'Столица Ассирии', difficulty: 'advanced' },
      { term: 'Тир', category: 'Места и география', hint: 'Финикийский город', difficulty: 'advanced' },
      { term: 'Сидон', category: 'Места и география', hint: 'Финикийский город', difficulty: 'advanced' },
      { term: 'Петра', category: 'Места и география', hint: 'Город в скалах', difficulty: 'advanced' },
      { term: 'Пелла', category: 'Места и география', hint: 'Город в Заиорданье', difficulty: 'advanced' },
      { term: 'Гераса', category: 'Места и география', hint: 'Город бесноватых', difficulty: 'advanced' },
      { term: 'Гадара', category: 'Места и география', hint: 'Город бесноватых', difficulty: 'advanced' },
      { term: 'Вифсаида', category: 'Места и география', hint: 'Родина апостолов', difficulty: 'advanced' },
      { term: 'Магдала', category: 'Места и география', hint: 'Родина Марии', difficulty: 'advanced' },
      { term: 'Наин', category: 'Места и география', hint: 'Город воскрешения', difficulty: 'advanced' },
      { term: 'Еммаус', category: 'Места и география', hint: 'Деревня на пути', difficulty: 'advanced' },
      { term: 'Лаодикия', category: 'Места и география', hint: 'Город церкви', difficulty: 'advanced' },
      { term: 'Сарды', category: 'Места и география', hint: 'Город церкви', difficulty: 'advanced' },
      { term: 'Пергам', category: 'Места и география', hint: 'Город церкви', difficulty: 'advanced' },
      { term: 'Фиатира', category: 'Места и география', hint: 'Город церкви', difficulty: 'advanced' },
      { term: 'Смирна', category: 'Места и география', hint: 'Город церкви', difficulty: 'advanced' },
      { term: 'Филадельфия', category: 'Места и география', hint: 'Город церкви', difficulty: 'advanced' },
    ],
  },
  {
    key: 'objects',
    title: 'Предметы и понятия',
    description: 'Библейские предметы, символы и понятия',
    words: [
      // Базовый режим - знакомые всем
      { term: 'Ковчег', category: 'Предметы и понятия', hint: 'Спасительное судно', difficulty: 'basic' },
      { term: 'Крест', category: 'Предметы и понятия', hint: 'Орудие казни', difficulty: 'basic' },
      { term: 'Хлеб', category: 'Предметы и понятия', hint: 'Основная пища', difficulty: 'basic' },
      { term: 'Вино', category: 'Предметы и понятия', hint: 'Виноградный напиток', difficulty: 'basic' },
      { term: 'Масло', category: 'Предметы и понятия', hint: 'Оливковое масло', difficulty: 'basic' },
      { term: 'Меч', category: 'Предметы и понятия', hint: 'Оружие воина', difficulty: 'basic' },
      { term: 'Щит', category: 'Предметы и понятия', hint: 'Защита воина', difficulty: 'basic' },
      { term: 'Труба', category: 'Предметы и понятия', hint: 'Сигнальный инструмент', difficulty: 'basic' },
      { term: 'Арфа', category: 'Предметы и понятия', hint: 'Струнный инструмент', difficulty: 'basic' },
      { term: 'Светильник', category: 'Предметы и понятия', hint: 'Источник света', difficulty: 'basic' },
      { term: 'Кувшин', category: 'Предметы и понятия', hint: 'Сосуд для воды', difficulty: 'basic' },
      { term: 'Чаша', category: 'Предметы и понятия', hint: 'Питьевой сосуд', difficulty: 'basic' },
      { term: 'Золото', category: 'Предметы и понятия', hint: 'Драгоценный металл', difficulty: 'basic' },
      { term: 'Серебро', category: 'Предметы и понятия', hint: 'Драгоценный металл', difficulty: 'basic' },
      { term: 'Мед', category: 'Предметы и понятия', hint: 'Сладкий продукт', difficulty: 'basic' },
      { term: 'Соль', category: 'Предметы и понятия', hint: 'Минеральная приправа', difficulty: 'basic' },
      
      // Усложненный режим - для знающих Библию
      { term: 'Скиния', category: 'Предметы и понятия', hint: 'Переносное святилище', difficulty: 'advanced' },
      { term: 'Жертвенник', category: 'Предметы и понятия', hint: 'Место жертвоприношений', difficulty: 'advanced' },
      { term: 'Венец', category: 'Предметы и понятия', hint: 'Царская корона', difficulty: 'advanced' },
      { term: 'Скипетр', category: 'Предметы и понятия', hint: 'Царский жезл', difficulty: 'advanced' },
      { term: 'Лук', category: 'Предметы и понятия', hint: 'Оружие дальнего боя', difficulty: 'advanced' },
      { term: 'Стрелы', category: 'Предметы и понятия', hint: 'Боевые снаряды', difficulty: 'advanced' },
      { term: 'Барабан', category: 'Предметы и понятия', hint: 'Ударный инструмент', difficulty: 'advanced' },
      { term: 'Флейта', category: 'Предметы и понятия', hint: 'Духовой инструмент', difficulty: 'advanced' },
      { term: 'Колокол', category: 'Предметы и понятия', hint: 'Звуковой сигнал', difficulty: 'advanced' },
      { term: 'Лампада', category: 'Предметы и понятия', hint: 'Масляный светильник', difficulty: 'advanced' },
      { term: 'Блюдо', category: 'Предметы и понятия', hint: 'Посуда для еды', difficulty: 'advanced' },
      { term: 'Нож', category: 'Предметы и понятия', hint: 'Режущий инструмент', difficulty: 'advanced' },
      { term: 'Топор', category: 'Предметы и понятия', hint: 'Рубящий инструмент', difficulty: 'advanced' },
      { term: 'Молот', category: 'Предметы и понятия', hint: 'Ударный инструмент', difficulty: 'advanced' },
      { term: 'Пила', category: 'Предметы и понятия', hint: 'Режущий инструмент', difficulty: 'advanced' },
      { term: 'Клещи', category: 'Предметы и понятия', hint: 'Захватывающий инструмент', difficulty: 'advanced' },
      { term: 'Кузнечные мехи', category: 'Предметы и понятия', hint: 'Инструмент кузнеца', difficulty: 'advanced' },
      { term: 'Горн', category: 'Предметы и понятия', hint: 'Кузнечная печь', difficulty: 'advanced' },
      { term: 'Наковальня', category: 'Предметы и понятия', hint: 'Кузнечная опора', difficulty: 'advanced' },
      { term: 'Тигель', category: 'Предметы и понятия', hint: 'Плавка металла', difficulty: 'advanced' },
      { term: 'Печь', category: 'Предметы и понятия', hint: 'Тепловая установка', difficulty: 'advanced' },
      { term: 'Очаг', category: 'Предметы и понятия', hint: 'Домашний огонь', difficulty: 'advanced' },
      { term: 'Дым', category: 'Предметы и понятия', hint: 'Продукт горения', difficulty: 'advanced' },
      { term: 'Пламя', category: 'Предметы и понятия', hint: 'Огонь', difficulty: 'advanced' },
      { term: 'Искра', category: 'Предметы и понятия', hint: 'Частица огня', difficulty: 'advanced' },
      { term: 'Пепел', category: 'Предметы и понятия', hint: 'Остаток горения', difficulty: 'advanced' },
      { term: 'Уголь', category: 'Предметы и понятия', hint: 'Топливо', difficulty: 'advanced' },
      { term: 'Дрова', category: 'Предметы и понятия', hint: 'Древесное топливо', difficulty: 'advanced' },
      { term: 'Солома', category: 'Предметы и понятия', hint: 'Стебли злаков', difficulty: 'advanced' },
      { term: 'Сено', category: 'Предметы и понятия', hint: 'Сушеная трава', difficulty: 'advanced' },
      { term: 'Семя', category: 'Предметы и понятия', hint: 'Зародыш растения', difficulty: 'advanced' },
      { term: 'Корень', category: 'Предметы и понятия', hint: 'Подземная часть растения', difficulty: 'advanced' },
      { term: 'Ветвь', category: 'Предметы и понятия', hint: 'Часть растения', difficulty: 'advanced' },
      { term: 'Лист', category: 'Предметы и понятия', hint: 'Зеленая часть растения', difficulty: 'advanced' },
      { term: 'Цветок', category: 'Предметы и понятия', hint: 'Орган размножения', difficulty: 'advanced' },
      { term: 'Плод', category: 'Предметы и понятия', hint: 'Результат цветения', difficulty: 'advanced' },
      { term: 'Трава', category: 'Предметы и понятия', hint: 'Низкорослые растения', difficulty: 'advanced' },
      { term: 'Куст', category: 'Предметы и понятия', hint: 'Низкорослое дерево', difficulty: 'advanced' },
      { term: 'Дерево', category: 'Предметы и понятия', hint: 'Многолетнее растение', difficulty: 'advanced' },
      { term: 'Лес', category: 'Предметы и понятия', hint: 'Множество деревьев', difficulty: 'advanced' },
      { term: 'Роща', category: 'Предметы и понятия', hint: 'Небольшой лес', difficulty: 'advanced' },
      { term: 'Дубрава', category: 'Предметы и понятия', hint: 'Дубовый лес', difficulty: 'advanced' },
      { term: 'Сад', category: 'Предметы и понятия', hint: 'Возделанный участок', difficulty: 'advanced' },
      { term: 'Виноградник', category: 'Предметы и понятия', hint: 'Сад винограда', difficulty: 'advanced' },
      { term: 'Оливковая роща', category: 'Предметы и понятия', hint: 'Сад оливок', difficulty: 'advanced' },
      { term: 'Пальмовая роща', category: 'Предметы и понятия', hint: 'Сад пальм', difficulty: 'advanced' },
      { term: 'Финиковая пальма', category: 'Предметы и понятия', hint: 'Плодовая пальма', difficulty: 'advanced' },
      { term: 'Смоковница', category: 'Предметы и понятия', hint: 'Инжирное дерево', difficulty: 'advanced' },
      { term: 'Гранат', category: 'Предметы и понятия', hint: 'Плодовое дерево', difficulty: 'advanced' },
      { term: 'Яблоня', category: 'Предметы и понятия', hint: 'Плодовое дерево', difficulty: 'advanced' },
      { term: 'Миндаль', category: 'Предметы и понятия', hint: 'Ореховое дерево', difficulty: 'advanced' },
      { term: 'Фисташка', category: 'Предметы и понятия', hint: 'Ореховое дерево', difficulty: 'advanced' },
      { term: 'Кедр', category: 'Предметы и понятия', hint: 'Хвойное дерево', difficulty: 'advanced' },
      { term: 'Кипарис', category: 'Предметы и понятия', hint: 'Хвойное дерево', difficulty: 'advanced' },
      { term: 'Сосна', category: 'Предметы и понятия', hint: 'Хвойное дерево', difficulty: 'advanced' },
      { term: 'Ель', category: 'Предметы и понятия', hint: 'Хвойное дерево', difficulty: 'advanced' },
      { term: 'Пихта', category: 'Предметы и понятия', hint: 'Хвойное дерево', difficulty: 'advanced' },
      { term: 'Можжевельник', category: 'Предметы и понятия', hint: 'Хвойный кустарник', difficulty: 'advanced' },
      { term: 'Мирт', category: 'Предметы и понятия', hint: 'Вечнозеленый кустарник', difficulty: 'advanced' },
      { term: 'Лавр', category: 'Предметы и понятия', hint: 'Вечнозеленое дерево', difficulty: 'advanced' },
      { term: 'Мирра', category: 'Предметы и понятия', hint: 'Ароматическая смола', difficulty: 'advanced' },
      { term: 'Ладан', category: 'Предметы и понятия', hint: 'Благовоние', difficulty: 'advanced' },
      { term: 'Смирна', category: 'Предметы и понятия', hint: 'Ароматическая смола', difficulty: 'advanced' },
      { term: 'Алоэ', category: 'Предметы и понятия', hint: 'Лечебное растение', difficulty: 'advanced' },
      { term: 'Полынь', category: 'Предметы и понятия', hint: 'Горькая трава', difficulty: 'advanced' },
      { term: 'Рута', category: 'Предметы и понятия', hint: 'Лечебная трава', difficulty: 'advanced' },
      { term: 'Иссоп', category: 'Предметы и понятия', hint: 'Очистительная трава', difficulty: 'advanced' },
      { term: 'Корица', category: 'Предметы и понятия', hint: 'Пряность', difficulty: 'advanced' },
      { term: 'Кориандр', category: 'Предметы и понятия', hint: 'Пряность', difficulty: 'advanced' },
      { term: 'Тмин', category: 'Предметы и понятия', hint: 'Пряность', difficulty: 'advanced' },
      { term: 'Укроп', category: 'Предметы и понятия', hint: 'Пряность', difficulty: 'advanced' },
      { term: 'Мята', category: 'Предметы и понятия', hint: 'Ароматическая трава', difficulty: 'advanced' },
      { term: 'Анис', category: 'Предметы и понятия', hint: 'Пряность', difficulty: 'advanced' },
      { term: 'Шафран', category: 'Предметы и понятия', hint: 'Дорогая пряность', difficulty: 'advanced' },
      { term: 'Мускатный орех', category: 'Предметы и понятия', hint: 'Пряность', difficulty: 'advanced' },
      { term: 'Кардамон', category: 'Предметы и понятия', hint: 'Пряность', difficulty: 'advanced' },
      { term: 'Имбирь', category: 'Предметы и понятия', hint: 'Пряность', difficulty: 'advanced' },
      { term: 'Куркума', category: 'Предметы и понятия', hint: 'Пряность', difficulty: 'advanced' },
      { term: 'Ваниль', category: 'Предметы и понятия', hint: 'Ароматическая пряность', difficulty: 'advanced' },
      { term: 'Гвоздика', category: 'Предметы и понятия', hint: 'Пряность', difficulty: 'advanced' },
      { term: 'Перец', category: 'Предметы и понятия', hint: 'Острая пряность', difficulty: 'advanced' },


      { term: 'Яд', category: 'Предметы и понятия', hint: 'Отравляющее вещество', difficulty: 'advanced' },
      { term: 'Противоядие', category: 'Предметы и понятия', hint: 'Средство от яда', difficulty: 'advanced' },


      { term: 'Медь', category: 'Предметы и понятия', hint: 'Красноватый металл', difficulty: 'advanced' },
      { term: 'Железо', category: 'Предметы и понятия', hint: 'Прочный металл', difficulty: 'advanced' },
      { term: 'Бронза', category: 'Предметы и понятия', hint: 'Сплав меди', difficulty: 'advanced' },
      { term: 'Свинец', category: 'Предметы и понятия', hint: 'Тяжелый металл', difficulty: 'advanced' },
      { term: 'Олово', category: 'Предметы и понятия', hint: 'Мягкий металл', difficulty: 'advanced' },
    ],
  },
  {
    key: 'culture',
    title: 'Культура (народные ценности и инструменты)',
    description: 'Библейские предметы культуры, инструменты и ценности',
    words: [
      // Базовый режим - знакомые всем
      { term: 'Арфа', category: 'Культура (народные ценности и инструменты)', hint: 'Музыкальный инструмент', difficulty: 'basic' },
      { term: 'Труба', category: 'Культура (народные ценности и инструменты)', hint: 'Духовой инструмент', difficulty: 'basic' },
      { term: 'Барабан', category: 'Культура (народные ценности и инструменты)', hint: 'Ударный инструмент', difficulty: 'basic' },
      { term: 'Флейта', category: 'Культура (народные ценности и инструменты)', hint: 'Духовой инструмент', difficulty: 'basic' },
      { term: 'Цимбалы', category: 'Культура (народные ценности и инструменты)', hint: 'Ударный инструмент', difficulty: 'basic' },
      { term: 'Лира', category: 'Культура (народные ценности и инструменты)', hint: 'Струнный инструмент', difficulty: 'basic' },
      
      // Усложненный режим - для знающих Библию
      { term: 'Шофар', category: 'Культура (народные ценности и инструменты)', hint: 'Рог для трубления', difficulty: 'advanced' },
      { term: 'Киннор', category: 'Культура (народные ценности и инструменты)', hint: 'Древняя лира', difficulty: 'advanced' },
      { term: 'Тоф', category: 'Культура (народные ценности и инструменты)', hint: 'Библейский барабан', difficulty: 'advanced' },
      { term: 'Халил', category: 'Культура (народные ценности и инструменты)', hint: 'Древняя флейта', difficulty: 'advanced' },
      { term: 'Мецлтаим', category: 'Культура (народные ценности и инструменты)', hint: 'Двойная флейта', difficulty: 'advanced' },
      { term: 'Менаним', category: 'Культура (народные ценности и инструменты)', hint: 'Погремушки', difficulty: 'advanced' },
      { term: 'Цилцелим', category: 'Культура (народные ценности и инструменты)', hint: 'Медные тарелки', difficulty: 'advanced' },
      { term: 'Невел', category: 'Культура (народные ценности и инструменты)', hint: 'Древняя арфа', difficulty: 'advanced' },
      { term: 'Асор', category: 'Культура (народные ценности и инструменты)', hint: 'Десятиструнный инструмент', difficulty: 'advanced' },
      { term: 'Угав', category: 'Культура (народные ценности и инструменты)', hint: 'Древний духовой инструмент', difficulty: 'advanced' },
    ],
  },
  {
    key: 'food',
    title: 'Еда',
    description: 'Библейские продукты питания и напитки',
    words: [
      // Базовый режим - знакомые всем
      { term: 'Хлеб', category: 'Еда', hint: 'Основная пища', difficulty: 'basic' },
      { term: 'Вино', category: 'Еда', hint: 'Напиток из винограда', difficulty: 'basic' },
      { term: 'Мёд', category: 'Еда', hint: 'Сладкий продукт пчёл', difficulty: 'basic' },
      { term: 'Молоко', category: 'Еда', hint: 'Питательная жидкость', difficulty: 'basic' },
      { term: 'Масло', category: 'Еда', hint: 'Жирная жидкость', difficulty: 'basic' },
      { term: 'Соль', category: 'Еда', hint: 'Минерал для вкуса', difficulty: 'basic' },
      { term: 'Вода', category: 'Еда', hint: 'Жизненная жидкость', difficulty: 'basic' },
      { term: 'Фрукты', category: 'Еда', hint: 'Сладкие плоды', difficulty: 'basic' },
      { term: 'Овощи', category: 'Еда', hint: 'Растительная пища', difficulty: 'basic' },
      { term: 'Рыба', category: 'Еда', hint: 'Морская пища', difficulty: 'basic' },
      
      // Усложненный режим - для знающих Библию
      { term: 'Манна', category: 'Еда', hint: 'Небесный хлеб', difficulty: 'advanced' },
      { term: 'Квас', category: 'Еда', hint: 'Кислый напиток', difficulty: 'advanced' },
      { term: 'Сыр', category: 'Еда', hint: 'Кисломолочный продукт', difficulty: 'advanced' },
      { term: 'Творог', category: 'Еда', hint: 'Кисломолочный продукт', difficulty: 'advanced' },
    ],
  },
  {
    key: 'clothing',
    title: 'Одежда',
    description: 'Библейская одежда и ткани',
    words: [
      // Базовый режим - знакомые всем
      { term: 'Одежда', category: 'Одежда', hint: 'Покрытие тела', difficulty: 'basic' },
      { term: 'Платье', category: 'Одежда', hint: 'Женская одежда', difficulty: 'basic' },
      { term: 'Пояс', category: 'Одежда', hint: 'Опоясывание', difficulty: 'basic' },
      { term: 'Платок', category: 'Одежда', hint: 'Ткань для головы', difficulty: 'basic' },
      { term: 'Покрывало', category: 'Одежда', hint: 'Покрытие', difficulty: 'basic' },
      
      // Усложненный режим - для знающих Библию
      { term: 'Ефод', category: 'Одежда', hint: 'Священническая одежда', difficulty: 'advanced' },
      { term: 'Наперсник', category: 'Одежда', hint: 'Нагрудный знак', difficulty: 'advanced' },
      { term: 'Митра', category: 'Одежда', hint: 'Священнический головной убор', difficulty: 'advanced' },
      { term: 'Риза', category: 'Одежда', hint: 'Священническая одежда', difficulty: 'advanced' },
      { term: 'Виссон', category: 'Одежда', hint: 'Льняная ткань', difficulty: 'advanced' },
      { term: 'Пурпур', category: 'Одежда', hint: 'Царская ткань', difficulty: 'advanced' },
      { term: 'Шелк', category: 'Одежда', hint: 'Дорогая ткань', difficulty: 'advanced' },
      { term: 'Кожа', category: 'Одежда', hint: 'Материал одежды', difficulty: 'advanced' },
      { term: 'Мех', category: 'Одежда', hint: 'Тёплая одежда', difficulty: 'advanced' },
    ],
  },
];

export function getAllWords(selectedCategoryKeys?: string[], includeAdvanced: boolean = false): AliasWord[] {
  const chosen = selectedCategoryKeys && selectedCategoryKeys.length > 0
    ? aliasCategories.filter(c => selectedCategoryKeys.includes(c.key))
    : aliasCategories;
  
  const allWords = chosen.flatMap(c => c.words);
  
  // Если включен усложненный режим, возвращаем все слова
  // Если выключен - только базовые
  return includeAdvanced ? allWords : allWords.filter(w => w.difficulty === 'basic');
}

export function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
